language: "ko-KR"

reviews:
  profile: "chill"
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  request_changes_workflow: false
  poem: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "jiin"
      - "main"
    path_filters:
      - "!build/**"
      - "!.gradle/**"
      - "!gradle/wrapper/gradle-wrapper.jar"

chat:
  auto_reply: true
