spring:
  application:
    name: kbti

  datasource:
    url: jdbc:h2:mem:kbtidb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true

kleague:
  player:
    csv-path: classpath:kleague_player_basic_stats.csv
