spring:
  application:
    name: kbti

  datasource:
    url: jdbc:h2:mem:kbtidb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false

  h2:
    console:
      enabled: false

kleague:
  player:
    csv-path: classpath:kleague_player_basic_stats.csv

kbti:
  api:
    allowed-origins:
      - "http://localhost:8080"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
